version: "3.8"
services:
  keycloak:
    image: carlovankessel/workouttracking/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_FRONTEND_URL: "http://localhost:8484"
    ports:
      - "8484:8484"
    networks:
      - workouttracking_network

  postgres:
    image: carlovankessel/workouttracking/postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - workouttracking_network

networks:
  workouttracking_network:
    driver: bridge